{{- if and .Values.prometheusStack.enabled (index .Values.prometheusStack "grafanaIngress" "enabled") }}
{{- $grafanaSvc := .Values.prometheusStack.grafanaServiceName | default (printf "%s-grafana" .Release.Name) }}
{{- $gi := .Values.prometheusStack.grafanaIngress }}
{{- $monitoringNs := index .Values "prometheus-stack" "namespaceOverride" | default "monitoring" }}
{{- if and $gi.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if and $gi.annotations (not (hasKey $gi.annotations "kubernetes.io/ingress.class")) }}
  {{- $_ := set $gi.annotations "kubernetes.io/ingress.class" $gi.className }}
  {{- end }}
{{- end }}
{{- if $gi.hosts }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "wiki-chart.fullname" . }}-grafana
  namespace: {{ $monitoringNs }}
  labels:
    {{- include "wiki-chart.labels" . | nindent 4 }}
    {{- with $gi.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $gi.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and $gi.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ $gi.className }}
  {{- end }}
  {{- if $gi.tls }}
  tls:
    {{- range $gi.tls }}
    - secretName: {{ .secretName }}
      hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $gi.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ $gi.path | default "/grafana" }}
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: {{ $gi.pathType | default "Prefix" }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $grafanaSvc }}
                port:
                  number: 80
              {{- else }}
              serviceName: {{ $grafanaSvc }}
              servicePort: 80
              {{- end }}
    {{- end }}
{{- end }}
{{- end }}
