apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: ${AWS_ACCOUNT_PROVISIONER_ROLE_ARN}
      username: account-provisioner
      groups:
        - account-provisioners
    - rolearn: ${AWS_MCP_JOB_SERVICE_ROLE_ARN}
      username: mcp-job-service
      groups:
        - mcp-job-services
    - rolearn: ${AWS_EKS_NODE_ROLE_ARN}
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
