---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ${TENANT_NAME}
  name: tenant-admin
rules:
- apiGroups: ["", "apps", "batch", "networking.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-admin-binding
  namespace: ${TENANT_NAME}
subjects:
- kind: ServiceAccount
  name: ${TENANT_NAME}-admin
  namespace: ${TENANT_NAME}
roleRef:
  kind: Role
  name: tenant-admin
  apiGroup: rbac.authorization.k8s.io
