---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ${TENANT_NAME}-quota
  namespace: ${TENANT_NAME}
spec:
  hard:
    requests.cpu: "${TENANT_CPU}"
    requests.memory: "${TENANT_RAM}"
    limits.cpu: "${TENANT_CPU_LIMIT}"
    limits.memory: "${TENANT_RAM_LIMIT}"
    persistentvolumeclaims: "${TENANT_PVC_LIMIT}"
    services: "${TENANT_SERVICE_LIMIT}"
    count/deployments.apps: "${TENANT_DEPLOYMENT_LIMIT}"
    count/statefulsets.apps: "${TENANT_STATEFULSET_LIMIT}"
