# this creates two profiles that are usable to 
kind: ConfigMap
apiVersion: v1
metadata:
  name: mig-parted-config
data:
  slice-4: |-
    version: v1
    sharing:
      timeSlicing:
        renameByDefault: true
        failRequestsGreaterThanOne: true
        resources:
          name: nvidia.com/gpu
          replicas: 4

  slice-10: |-
    version: v1
    sharing:
      timeSlicing:
        renameByDefault: true
        failRequestsGreaterThanOne: true
        resources:
          name: nvidia.com/gpu
          replicas: 10

    