apiVersion: v1
kind: Pod
metadata:
  name: "NON GPU POD"
  namespace: default
  labels:
    app: "NON GPU POD"
spec:
  containers:
  - name: NON GPU POD
    image: "debian-slim:latest"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: NON GPU POD
          key: DB_HOST
    ports:
    - containerPort:  80
      name:  http
    volumeMounts:
    - name: localtime
      mountPath: /etc/localtime
  tolerations:
    - key: "nvidia.com/gpu"
      operator: Exists
      effect: NoSchedule
  volumes:
    - name: localtime
      hostPath:
        path: /usr/share/zoneinfo/Asia/Shanghai
  restartPolicy: Always